<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create('id_ID');
        DB::table('products')->insert([
            [
                'productID' => $faker->uuid,
                'productName' => 'Kebaya Encim Sleeveless',
                'productPrice' => 259000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Suar merupakan koleksi kolaborasi Dama Kara x Putri Marino. Terinspirasi dari Batik Sekar Jagad yang merupakan batik khas Lasem. Motif dari Batik Sekar Jagad menggambarkan keindahan keberagaman berbagai suku bangsa dan dimaknai juga sebagai bunga kehidupan. Suar menjadi sebuah pemantik yang menyalakan keistimewaan dalam diri yang tumbuh untuk menggerakkan hal baik untuk sekitar yang Dama Kara dan Putri Marino sampaikan melalui karya sandang bertajuk Tentang Suar.',
                'productWeight' => 200,
                'productPicturePath' => '["public\/product\/1.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Suar Obi Belt',
                'productPrice' => 89000,
                'productCategory' => 'Aksesoris',
                'productDescription' => 'Suar menjadi sebuah pemantik yang menyalakan keistimewaan dalam diri yang tumbuh untuk menggerakkan hal baik untuk sekitar yang Dama Kara dan Putri Marino sampaikan melalui karya sandang bertajuk Tentang Suar.',
                'productWeight' => 50,
                'productPicturePath' => '["public\/product\/2.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Obi Belt Kinasih',
                'productPrice' => 75000,
                'productCategory' => 'Aksesoris',
                'productDescription' => 'Koleksi batik Dama Kara dibuat oleh pengrajin kami dengan proses tradisional, tiap helai kainnya memiliki keunikannya masing-masing yang dimungkinkan sedikit perbedaan pada warna atau motifnya.',
                'productWeight' => 50,
                'productPicturePath' => '["public\/product\/3.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Gayatri Set Outer',
                'productPrice' => 379000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Gayatri hadir sebagai pengingat bahwa setiap insan diciptakan dengan keistimewaannya masing-masing. Dua garis pada motif Gayatri memiliki makna dualisme yaitu dibalik sisi kurang yang terlihat, tiap insan dianugerahi kelebihan oleh sang pencipta, pun demikian dengan teman-teman autism, dibalik kekurangannya terdapat kelebihan yang mereka miliki.',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/4.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Basic Inner Top ',
                'productPrice' => 109000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Bisa digunakan untuk inner saat menggunakan koleksi Dama Kara. Terbuat dari bahan rayon eco twill yang bukan hanya nyaman dipakai tapi juga baik untuk bumi. Rayon eco twill berbeda dengan rayon biasa, cenderung lebih tebal, dengan tekstur twill, namun sangat nyaman digunakan karena terbuat dari material 100% cotton.',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/5.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Dama Kara Wide Pants',
                'productPrice' => 169000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'memiliki potongan lebar dan nyaman.  Harganya di situs web mereka adalah Rp 169.000 (diskon dari Rp 189.000) atau sekitar $12 USD.  Celana ini terbuat dari bahan yang bagus dan kuat, cocok untuk dipakai di luar ruangan maupun di dalam ruangan.',
                'productWeight' => 250,
                'productPicturePath' => '["public\/product\/6.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Gayatri Sweater',
                'productPrice' => 249000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Dua garis pada motif Gayatri memiliki makna dualisme yaitu dibalik sisi kurang yang terlihat, tiap insan dianugerahi kelebihan oleh sang pencipta, pun demikian dengan teman-teman autism, dibalik kekurangannya terdapat kelebihan yang mereka miliki.',
                'productWeight' => 150,
                'productPicturePath' => '["public\/product\/7.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Hanna Printed Sleeves',
                'productPrice' => 239000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Outer seri terbaru dari dama kara, memadukan bahan dengan tekstur crinkle dengan teknologi airflow yang nyaman, dipadukan dengan rayon eco twill printing dari motif teman teman istimewa di kelas terapi menggambar. karena kami yakin, berkarya tak mengenal keterbatasan.',
                'productWeight' => 50,
                'productPicturePath' => '["public\/product\/8.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Brown HeavyPants',
                'productPrice' => 200000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'memiliki potongan lebar dan nyaman.  Harganya di situs web mereka adalah Rp 169.000 (diskon dari Rp 189.000) atau sekitar $12 USD.  Celana ini terbuat dari bahan yang bagus dan kuat, cocok untuk dipakai di luar ruangan maupun di dalam ruangan.',
                'productWeight' => 300,
                'productPicturePath' => '["public\/product\/9.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'productID' => $faker->uuid,
                'productName' => 'Dama Kara Scrunchie',
                'productPrice' => 12900,
                'productCategory' => 'Aksesoris',
                'productDescription' => 'Scrunchie adalah ikat rambut elastis berlapis kain yang digunakan untuk mengikat jenis rambut sedang hingga panjang.',
                'productWeight' => 10,
                'productPicturePath' => '["public\/product\/10.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Puffy Eco Linen Blouse',
                'productPrice' => 299000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Puffy Eco Linen Blouse adalah blus wanita dengan model lengan balon yang mengembang. Blus ini terbuat dari bahan linen ramah lingkungan yang ringan dan adem saat dipakai.',
                'productWeight' => 200,
                'productPicturePath' => '["public\/product\/11.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Dama Kara Skirt Jeans',
                'productPrice' => 299000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'The Dama Kara Skirt Jeans adalah rok yang terbuat dari bahan denim atau menyerupai denim. Rok ini tersedia dalam setidaknya tiga warna: Kinasih Olive, Gayatri Navy, dan Polkadot. Berdasarkan deskripsi ukuran (Allsize fit to XL), tampaknya rok ini memiliki ukuran yang bisa dipakai oleh kebanyakan orang.',
                'productWeight' => 300,
                'productPicturePath' => '["public\/product\/12.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Rumi Set Outer',
                'productPrice' => 379000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Koleksi batik Dama Kara dibuat oleh pengrajin kami dengan proses tradisional, tiap helai kainnya memiliki keunikannya masing-masing yang dimungkinkan sedikit perbedaan pada warna atau motifnya.',
                'productWeight' => 150,
                'productPicturePath' => '["public\/product\/13.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Hapsari Cardigan',
                'productPrice' => 279000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Kolaborasi Dama Kara dengan Prita Ghozie yang mengembangkan motif dengan mengangkat pengalaman dan nilai-nilai hidup sehari-hari yang kemudian dituangkan kedalam #DamaKaraHapsari. Motif kawung bermakna kesempurnaan, kemurnian dan kesucian. Motif yang membentuk segitiga bermakna sebagai bentuk keseimbangan dalam hidup, serta motif kembang kawung yang dimaknai sebagai mekarnya pencapaian dari setiap harapan seiring mekarnya bunga tersebut.',
                'productWeight' => 250,
                'productPicturePath' => '["public\/product\/14.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Dama Kara Masker Batik',
                'productPrice' => 12900,
                'productCategory' => 'Aksesoris',
                'productDescription' => 'Motif dan warna pada set series ini dibuat secara tradisional dengan proses cap, ikat, jumput, dan proses pewarnaan serta pengeringan secara tradisional. menjadi komitmen kami untuk mengangkat kain tradisional indonesia dalam koleksi volume ganjil, agar para pengrajin bisa terus berkarya dan memberikan yang terbaik bagi keluarganya.',
                'productWeight' => 10,
                'productPicturePath' => '["public\/product\/15.jpg"]',
                'forGender' => 'Pria',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Suar Bucket Hat',
                'productPrice' => 129000,
                'productCategory' => 'Aksesoris',
                'productDescription' => 'Motif dari Batik Sekar Jagad menggambarkan keindahan keberagaman berbagai suku bangsa dan dimaknai juga sebagai bunga kehidupan. Suar menjadi sebuah pemantik yang menyalakan keistimewaan dalam diri yang tumbuh untuk menggerakkan hal baik untuk sekitar yang Dama Kara dan Putri Marino sampaikan melalui karya sandang bertajuk Tentang Suar.',
                'productWeight' => 50,
                'productPicturePath' => '["public\/product\/16.jpg"]',
                'forGender' => 'Pria',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Multiway Twilly Batik',
                'productPrice' => 59000,
                'productCategory' => 'Aksesoris',
                'productDescription' => 'Dengan meyakini bahwa setiap hal baik yang dimulai dari langkah kecil. Sebuah perwujudan kepedulian dari Dama Kara terhadap bumi. Mengubah yang mulanya sekedar limbah menjadi sebuah kebermanfaatan dengan menghadirkan produk aksesoris yang memanfaatkan sisa kain batik Dama Kara.',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/17.jpg","public\/product\/17-2.jpg","public\/product\/17-3.jpg", "public\/product\/17-4.jpg", "public\/product\/17-5.jpg"]',
                'forGender' => 'Pria',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kaimana Embroidery Kids',
                'productPrice' => 289000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Motif yang terinspirasi dari tameng perang suku asmat sebagai bentuk doa kepada dewa-dewa untuk keselamatan suku asmat sebelum dimulainya perang. Bentuk segitiga yang sebagai simbol stabilitas karena bentuknya yang meruncing keatas dapat menjadi suatu penunjuk arah atas sebuah pencapaian dan tujuan. Bentuk segitiga kebawah yang menyimbolkan ke feminiman dan sebagai sosok yang sederhana.',
                'productWeight' => 150,
                'productPicturePath' => '["public\/product\/18.jpg", "public\/product\/18-2.jpg", "public\/product\/18-3.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kinasih Shirt Kids',
                'productPrice' => 229000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Kinasih terinspirasi dari motif jumputan dan tritik yang merupakan motif tradisional khas Indonesia. Bentuk yang diambil dari 2 bentuk dasar paling sederhana berupa titik dan garis, yang memiliki makna agar manusia memiliki sifat mendasar yang sederhana dan tidak serakah. Arah garis pada motif yang memiliki arti hubungan manusia dengan lainnya selalu diseimbangkan agar terjadi harmoni dalam hidupnya.',
                'productWeight' => 75,
                'productPicturePath' => '["public\/product\/19.jpg", "public\/product\/19-2.jpg", "public\/product\/19-3.jpg", "public\/product\/19-4.jpg"]',
                'forGender' => 'Pria',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kaimana Dress Kids',
                'productPrice' => 289000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Koleksi batik Dama Kara dibuat oleh pengrajin kami dengan proses tradisional, tiap helai kainnya memiliki keunikannya masing-masing yang dimungkinkan sedikit perbedaan pada warna atau motifnya.',
                'productWeight' => 75,
                'productPicturePath' => '["public\/product\/20.jpg", "public\/product\/20-2.jpg", "public\/product\/20-3.jpg", "public\/product\/20-4.jpg", "public\/product\/20-5.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kaimana Short Pants',
                'productPrice' => 159000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Koleksi batik Dama Kara dibuat oleh pengrajin kami dengan proses tradisional, tiap helai kainnya memiliki keunikannya masing-masing yang dimungkinkan sedikit perbedaan pada warna atau motifnya.',
                'productWeight' => 150,
                'productPicturePath' => '["public\/product\/21.jpg", "public\/product\/21-2.jpg", "public\/product\/21-3.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Dama Kara Pants Jeans',
                'productPrice' => 149000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Model : Short Pants Jeans, Long Pants Jeans Color : Black Fabric : Jeans Soft Size : Allsize fit to XL Short Pants Jeans : Panjang 54 cm Pesak 30 cm Pinggang 22-50 cm Long Pants Jeans : Panjang 89 cm Pesak 33 cm Pinggang 22-48 cm',
                'productWeight' => 250,
                'productPicturePath' => '["public\/product\/22.jpg", "public\/product\/22-2.jpg", "public\/product\/22-3.jpg", "public\/product\/22-4.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Tiara Long Pants',
                'productPrice' => 109000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Dama Kara x Tiara Our Dream Sesuai dengan semangat yang ingin kami bagi, bahwa berkarya tidak mengenal keterbatasan. Pada koleksi kali ini kami mengangkat gambar karya Tiara, salah satu teman istimewa kami di @ourdreamindonesia. Gambar gunung dan bunga karya Tiara tersebut kami aplikasikan pada artikel ini untuk Teman Dama Kara bawa dalam keseharian, juga sebagai pengingat bahwa kita semua istimewa?',
                'productWeight' => 150,
                'productPicturePath' => '["public\/product\/23.jpg", "public\/product\/23-2.jpg", "public\/product\/23-3.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kala Sarung',
                'productPrice' => 249000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Sebuah kolaborasi Dama Kara dan Bumi Kiwari yang terinspirasi dari beberapa elemen, yaitu tanah, air, biji kopi, dan komunitas yang beriringan menjaga, merawat, untuk menjadikan ekosistem yang saling memberikan kebermanfaatan. Sebagai wujud bahwa hal baik dimulai dari rumah dan tanah kita yang dituangkan dalam karya sandang bertajuk “Kala”',
                'productWeight' => 50,
                'productPicturePath' => '["public\/product\/24.jpg"]',
                'forGender' => 'Pria',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kala Pocket Shirt',
                'productPrice' => 279000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Sebuah kolaborasi Dama Kara dan Bumi Kiwari yang terinspirasi dari beberapa elemen, yaitu tanah, air, biji kopi, dan komunitas yang beriringan menjaga, merawat, untuk menjadikan ekosistem yang saling memberikan kebermanfaatan. Sebagai wujud bahwa hal baik dimulai dari rumah dan tanah kita yang dituangkan dalam karya sandang bertajuk “Kala”',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/25.jpg"]',
                'forGender' => 'Pria',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kala Outer Batwing',
                'productPrice' => 229000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Sebuah kolaborasi Dama Kara dan Bumi Kiwari yang terinspirasi dari beberapa elemen, yaitu tanah, air, biji kopi, dan komunitas yang beriringan menjaga, merawat, untuk menjadikan ekosistem yang saling memberikan kebermanfaatan. Sebagai wujud bahwa hal baik dimulai dari rumah dan tanah kita yang dituangkan dalam karya sandang bertajuk “Kala”',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/26.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Embroidery Outer Sleeveless',
                'productPrice' => 359000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Sebuah kolaborasi Dama Kara dan Bumi Kiwari yang terinspirasi dari beberapa elemen, yaitu tanah, air, biji kopi, dan komunitas yang beriringan menjaga, merawat, untuk menjadikan ekosistem yang saling memberikan kebermanfaatan. Sebagai wujud bahwa hal baik dimulai dari rumah dan tanah kita yang dituangkan dalam karya sandang bertajuk “Kala”',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/27.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kinasih Blazer',
                'productPrice' => 269000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Kinasih terinspirasi dari motif jumputan dan tritik yang merupakan motif tradisional khas Indonesia. Bentuk yang diambil dari 2 bentuk dasar paling sederhana berupa titik dan garis, yang memiliki makna agar manusia memiliki sifat mendasar yang sederhana dan tidak serakah. Arah garis pada motif yang memiliki arti hubungan manusia dengan lainnya selalu diseimbangkan agar terjadi harmoni dalam hidupnya.',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/28.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Basic Dress',
                'productPrice' => 169000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Untuk melengkapi tampilan, kami hadirkan basic dress yang bisa dipadukan dengan outer series kami. Dilengkapi dengan tali yang bisa dipasang atau lepas sesuai dengan look yang kamu inginkan, serta kantong dibagian kanan dan kiri.',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/29.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Blouse Two Tone Pleats',
                'productPrice' => 229000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Meyakini bahwa setiap insan terlahir dengan keistimewaannya masing-masing, Dama Kara berkolaborsi dengan teman penyandang autis untuk diangkat karyanya ke dalam koleksi Dama Kara. Dari hasil penjualan produk teman penyandang autis akan memperoleh royalti setiap bulannya.',
                'productWeight' => 150,
                'productPicturePath' => '["public\/product\/30.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kinasih Button Top',
                'productPrice' => 209000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Kinasih terinspirasi dari motif jumputan dan tritik yang merupakan motif tradisional khas Indonesia. Bentuk yang diambil dari 2 bentuk dasar paling sederhana berupa titik dan garis, yang memiliki makna agar manusia memiliki sifat mendasar yang sederhana dan tidak serakah. Arah garis pada motif yang memiliki arti hubungan manusia dengan lainnya selalu diseimbangkan agar terjadi harmoni dalam hidupnya.',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/31.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Dama Kara Kimono',
                'productPrice' => 359000,
                'productCategory' => 'Atasan',
                'productDescription' => 'kimono reversible bisa digunakan bolak balik kimono gayatri black memadukan warna hitam di sisi satunya, dan dominan motif gayatri di sisi baliknya. kimono lembayung navy memadukan warna soft jeans dan motif lembayung di sisi yang berbeda.',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/32.jpg"]',
                'forGender' => 'Pria',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Gayatri Outer Kids',
                'productPrice' => 229000,
                'productCategory' => 'Atasan',
                'productDescription' => 'Gayatri hadir sebagai pengingat bahwa setiapinsan diciptakan dengan keistimewaannya masing-masing. Dua garis pada motif Gayatri memiliki makna dualisme yaitu dibalik sisi kurang yang terlihat, tiap insan dianugerahi kelebihan oleh sang pencipta, pun demikian dengan teman-teman autism, dibalik kekurangannya terdapat kelebihan yang mereka miliki.',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/33.jpg"]',
                'forGender' => 'Pria',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kaimana Long Pants',
                'productPrice' => 229000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Motif yang terinspirasi dari tameng perang suku asmat sebagai bentuk doa kepada dewa-dewa untuk keselamatan suku asmat sebelum dimulainya perang. Bentuk segitiga yang sebagai simbol stabilitas karena bentuknya yang meruncing keatas dapat menjadi suatu penunjuk arah atas sebuah pencapaian dan tujuan. Bentuk segitiga kebawah yang menyimbolkan ke feminiman dan sebagai sosok yang sederhana.',
                'productWeight' => 250,
                'productPicturePath' => '["public\/product\/34.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kaimana Skirt',
                'productPrice' => 229000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Koleksi batik Dama Kara dibuat oleh pengrajin kami dengan proses tradisional, tiap helai kainnya memiliki keunikannya masing-masing yang dimungkinkan sedikit perbedaan pada warna atau motifnya.',
                'productWeight' => 150,
                'productPicturePath' => '["public\/product\/35.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kara Asha Short Pants',
                'productPrice' => 175000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Meyakini bahwa setiap insan terlahir dengan keistimewaannya masing-masing, Dama Kara berkolaborsi dengan teman penyandang autis untuk diangkat karyanya ke dalam koleksi Dama Kara. Dari hasil penjualan produk teman penyandang autis akan memperoleh royalti setiap bulannya.',
                'productWeight' => 75,
                'productPicturePath' => '["public\/product\/36.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Rona Bian Coat Jeans',
                'productPrice' => 329000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Abi dan Rian. Dua teman istimewa dari ATC (Art Therapy Center) Widyatama, bersama dengan Dama Kara, mencipta motif dari perpaduan warna diatas media, yang juga dikenal dengan teknik suminagashi. Rona warna demi warna memaknai setiap lebh dan kurang dari tiap insan yang berpadu menjadi sebuah keistimewaan.',
                'productWeight' => 250,
                'productPicturePath' => '["public\/product\/37.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Rona Bian Short Pants',
                'productPrice' => 299000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Rona BiAn. Begitu kami menyebut koleksi kolaborasi bersana Abi dan Rian. Yang semoga bisa menjadi rona cerita dalam keseharian Teman Dama Kara.',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/38.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Hapsari Black Formal',
                'productPrice' => 229000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Kolaborasi Dama Kara dengan Prita Ghozie yang mengembangkan motif dengan mengangkat pengalaman dan nilai-nilai hidup sehari-hari yang kemudian dituangkan kedalam #DamaKaraHapsari. Motif kawung bermakna kesempurnaan, kemurnian dan kesucian. Motif yang membentuk segitiga bermakna sebagai bentuk keseimbangan dalam hidup, serta motif kembang kawung yang dimaknai sebagai mekarnya pencapaian dari setiap harapan seiring mekarnya bunga tersebut.',
                'productWeight' => 250,
                'productPicturePath' => '["public\/product\/39.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Gayatri Skort Pants',
                'productPrice' => 249000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Koleksi batik Dama Kara dibuat oleh pengrajin kami dengan proses tradisional, tiap helai kainnya memiliki keunikannya masing-masing yang dimungkinkan sedikit perbedaan pada warna atau motifnya.',
                'productWeight' => 120,
                'productPicturePath' => '["public\/product\/40.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kinasih Long Pants',
                'productPrice' => 229000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Kinasih terinspirasi dari motif jumputan dan tritik yang merupakan motif tradisional khas Indonesia. Bentuk yang diambil dari 2 bentuk dasar paling sederhana berupa titik dan garis, yang memiliki makna agar manusia memiliki sifat mendasar yang sederhana dan tidak serakah. Arah garis pada motif yang memiliki arti hubungan manusia dengan lainnya selalu diseimbangkan agar terjadi harmoni dalam hidupnya.',
                'productWeight' => 200,
                'productPicturePath' => '["public\/product\/41.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kinasih Short Pants',
                'productPrice' => 219000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Koleksi batik Dama Kara dibuat oleh pengrajin kami dengan proses tradisional, tiap helai kainnya memiliki keunikannya masing-masing yang dimungkinkan sedikit perbedaan pada warna atau motifnya.',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/42.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kinasih Blouse Pants',
                'productPrice' => 219000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Kinasih terinspirasi dari motif jumputan dan tritik yang merupakan motif tradisional khas Indonesia. Bentuk yang diambil dari 2 bentuk dasar paling sederhana berupa titik dan garis, yang memiliki makna agar manusia memiliki sifat mendasar yang sederhana dan tidak serakah. Arah garis pada motif yang memiliki arti hubungan manusia dengan lainnya selalu diseimbangkan agar terjadi harmoni dalam hidupnya.',
                'productWeight' => 100,
                'productPicturePath' => '["public\/product\/43.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Asha Pajama Pants',
                'productPrice' => 110000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Meyakini bahwa setiap insan terlahir dengan keistimewaannya masing-masing, Dama Kara berkolaborsi dengan teman penyandang autis untuk diangkat karyanya ke dalam koleksi Dama Kara. Dari hasil penjualan produk teman penyandang autis akan memperoleh royalti setiap bulannya.',
                'productWeight' => 75,
                'productPicturePath' => '["public\/product\/44.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kaimana Sarung',
                'productPrice' => 229000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Koleksi batik Dama Kara dibuat oleh pengrajin kami dengan proses tradisional, tiap helai kainnya memiliki keunikannya masing-masing yang dimungkinkan sedikit perbedaan pada warna atau motifnya.',
                'productWeight' => 50,
                'productPicturePath' => '["public\/product\/45.jpg"]',
                'forGender' => 'Pria',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kala Skirt',
                'productPrice' => 249000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Sebuah kolaborasi Dama Kara dan Bumi Kiwari yang terinspirasi dari beberapa elemen, yaitu tanah, air, biji kopi, dan komunitas yang beriringan menjaga, merawat, untuk menjadikan ekosistem yang saling memberikan kebermanfaatan. Sebagai wujud bahwa hal baik dimulai dari rumah dan tanah kita yang dituangkan dalam karya sandang bertajuk “Kala”',
                'productWeight' => 50,
                'productPicturePath' => '["public\/product\/46.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kala Dark Skirt',
                'productPrice' => 279000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Sebuah kolaborasi Dama Kara dan Bumi Kiwari yang terinspirasi dari beberapa elemen, yaitu tanah, air, biji kopi, dan komunitas yang beriringan menjaga, merawat, untuk menjadikan ekosistem yang saling memberikan kebermanfaatan. Sebagai wujud bahwa hal baik dimulai dari rumah dan tanah kita yang dituangkan dalam karya sandang bertajuk “Kala”',
                'productWeight' => 50,
                'productPicturePath' => '["public\/product\/47.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Kara Suar Skirt',
                'productPrice' => 269000,
                'productCategory' => 'Bawahan',
                'productDescription' => 'Suar merupakan koleksi kolaborasi Dama Kara x Putri Marino. Terinspirasi dari Batik Sekar Jagad yang merupakan batik khas Lasem. Motif dari Batik Sekar Jagad menggambarkan keindahan keberagaman berbagai suku bangsa dan dimaknai juga sebagai bunga kehidupan. Suar menjadi sebuah pemantik yang menyalakan keistimewaan dalam diri yang tumbuh untuk menggerakkan hal baik untuk sekitar yang Dama Kara dan Putri Marino sampaikan melalui karya sandang bertajuk Tentang Suar.',
                'productWeight' => 50,
                'productPicturePath' => '["public\/product\/48.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Rona Bian Bucket Hat',
                'productPrice' => 129000,
                'productCategory' => 'Aksesoris',
                'productDescription' => 'Abi dan Rian. Dua teman istimewa dari ATC (Art Therapy Center) Widyatama, bersama dengan Dama Kara, mencipta motif dari perpaduan warna diatas media, yang juga dikenal dengan teknik suminagashi. Rona warna demi warna memaknai setiap lebh dan kurang dari tiap insan yang berpadu menjadi sebuah keistimewaan.',
                'productWeight' => 25,
                'productPicturePath' => '["public\/product\/49.jpg", "public\/product\/49-2.jpg", "public\/product\/49-3.jpg", "public\/product\/49-4.jpg"]',
                'forGender' => 'Pria',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Sticker Sheet',
                'productPrice' => 30000,
                'productCategory' => 'Aksesoris',
                'productDescription' => 'Kolaborasi dari Dama Kara x Damarakhma x Our Dream Indonesia menghadirkan sticker dan keychain yang mengangkat karya hasil terapi menggambar dari teman-teman penyandang autis di @ourdreamindonesia yang kemudian diterjemahkan menjadi gambar digital oleh Damarakhma.',
                'productWeight' => 5,
                'productPicturePath' => '["public\/product\/50.jpg"]',
                'forGender' => 'Pria',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Laras Bucket Hat',
                'productPrice' => 99000,
                'productCategory' => 'Aksesoris',
                'productDescription' => 'Koleksi batik Dama Kara dibuat oleh pengrajin kami dengan proses tradisional, tiap helai kainnya memiliki keunikannya masing-masing yang dimungkinkan sedikit perbedaan pada warna atau motifnya.',
                'productWeight' => 50,
                'productPicturePath' => '["public\/product\/51.jpg", "public\/product\/51-2.jpg", "public\/product\/51-3.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'productID' => $faker->uuid,
                'productName' => 'Tiara Bag',
                'productPrice' => 79000,
                'productCategory' => 'Aksesoris',
                'productDescription' => 'Dama Kara x Tiara Our Dream Sesuai dengan semangat yang ingin kami bagi, bahwa berkarya tidak mengenal keterbatasan. Pada koleksi kali ini kami mengangkat gambar karya Tiara, salah satu teman istimewa kami di @ourdreamindonesia. Gambar gunung dan bunga karya Tiara tersebut kami aplikasikan pada artikel ini untuk Teman Dama Kara bawa dalam keseharian, juga sebagai pengingat bahwa kita semua istimewa?',
                'productWeight' => 25,
                'productPicturePath' => '["public\/product\/52.jpg", "public\/product\/52-2.jpg", "public\/product\/52-3.jpg", "public\/product\/52-4.jpg", "public\/product\/52-5.jpg"]',
                'forGender' => 'Wanita',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
